from pathlib import Path
import re, uuid, hashlib, sys

if len(sys.argv) != 3:
    raise SystemExit('usage: finalize_carrier.py INPUT.kicad_pcb OUTPUT.kicad_pcb')
src=Path(sys.argv[1]); out=Path(sys.argv[2])
s=src.read_text()
EXPECTED_IN='d76be0c4625d4a34c3e5a09d863da20c15aa4491002270aa1ff017080ce78dda'
if hashlib.sha256(src.read_bytes()).hexdigest()!=EXPECTED_IN:
    raise SystemExit('input board SHA mismatch')

def blocks(text, token):
    found=[]
    pat=re.compile(r'(?m)^([ \t]*)\('+re.escape(token)+r'\b')
    pos=0
    while True:
        m=pat.search(text,pos)
        if not m: break
        st=m.start()+len(m.group(1)); depth=0; i=st; ins=False; esc=False
        while i<len(text):
            c=text[i]
            if ins:
                if esc: esc=False
                elif c=='\\': esc=True
                elif c=='"': ins=False
            else:
                if c=='"': ins=True
                elif c=='(': depth+=1
                elif c==')':
                    depth-=1
                    if depth==0:
                        found.append((st,i+1)); pos=i+1; break
            i+=1
        else:
            raise SystemExit(f'unclosed {token} block')
    return found

# Hide autogenerated footprint references/values and move autogenerated outline rectangles to Fab.
for st,en in reversed(blocks(s,'footprint')):
    b=s[st:en]
    b=re.sub(r'(?m)^(\s*\(property "(?:Reference|Value)"[^\n]*\(layer "F\.SilkS"\))(\))\s*$',r'\1 hide\2',b)
    b=re.sub(r'(\(fp_rect\b.*?\(layer )"F\.SilkS"(\))',r'\1"F.Fab"\2',b,flags=re.S)
    s=s[:st]+b+s[en:]

# Make every human-facing silkscreen label at least 0.85 mm tall.
for st,en in reversed(blocks(s,'gr_text')):
    b=s[st:en]
    if '(layer "F.SilkS")' in b:
        def grow(m):
            a=float(m.group(1)); c=float(m.group(2))
            return f'(size {max(a,0.85):g} {max(c,0.85):g})'
        b=re.sub(r'\(size ([0-9.]+) ([0-9.]+)\)',grow,b)
        s=s[:st]+b+s[en:]

# Move C3, the 100 nF AHCT decoupler, adjacent to the RGB buffer and rotate it horizontal.
for st,en in reversed(blocks(s,'footprint')):
    b=s[st:en]
    if '(property "Reference" "C3"' in b:
        b=re.sub(r'\(at\s+75(?:\.00)?\s+102\.50\s+90\)', '(at 72.5 100.5 0)', b, count=1)
        b=b.replace('(at 0 -1.8 90)','(at 0 -1.8 0)').replace('(at 0 1.8 90)','(at 0 1.8 0)')
        b=b.replace('(at -1.4 0 90)','(at -1.4 0 0)').replace('(at 1.4 0 90)','(at 1.4 0 0)')
        s=s[:st]+b+s[en:]
        break

def seginfo(b):
    def xy(which):
        m=re.search(r'\('+which+r'\s+([0-9.]+)\s+([0-9.]+)\)',b)
        return tuple(map(float,m.groups())) if m else None
    lm=re.search(r'\(layer "([FB]\.Cu)"\)',b)
    nm=re.search(r'\(net\s+(\d+)\)',b)
    return xy('start'),xy('end'),lm.group(1) if lm else None,int(nm.group(1)) if nm else None

# Remove source routes superseded by the safe RGB power and AUX12 routing below.
old5={
    ((69.1,101.5),(73.6,101.5)),
    ((73.6,101.5),(88.0,101.5)),
    ((88.0,101.5),(88.0,103.0)),
    ((74.0,92.0),(74.0,101.1)),
    ((74.0,101.1),(75.0,101.1)),
}
for st,en in reversed(blocks(s,'segment')):
    b=s[st:en]; a,z,l,n=seginfo(b)
    remove=(n==2 and (a,z) in old5) or (n==14 and l=='B.Cu')
    if remove:
        s=s[:st]+s[en:]

# Remove the now-obsolete AUX12 layer-change via at the field pad.
for st,en in reversed(blocks(s,'via')):
    b=s[st:en]
    if '(net 14)' in b and re.search(r'\(at\s+43(?:\.0+)?\s+74(?:\.0+)?\)', b):
        s=s[:st]+s[en:]

# Original ground pours stopped at y=98 despite the expanded 109 mm board edge.
# Extend both planes to y=108, retaining 1 mm edge margin.
s=s.replace('(xy 128 98) (xy 2 98)', '(xy 128 108) (xy 2 108)')

uc=0
def U():
    global uc
    uc+=1
    return str(uuid.uuid5(uuid.NAMESPACE_DNS,f'esp32-carrier-final-v2-{uc}'))
def seg(a,b,w,l,n):
    return f'  (segment (start {a}) (end {b}) (width {w}) (layer "{l}") (net {n}) (uuid "{U()}"))\n'
def via(a,n):
    return f'  (via (at {a}) (size 1.0) (drill 0.5) (layers "F.Cu" "B.Cu") (net {n}) (uuid "{U()}"))\n'

new='\n'
# +5V: feed RGB buffer and C3 from the main B.Cu 5V backbone without crossing GND.
new+=seg('69.1 101.5','71.1 100.5','0.50','F.Cu',2)
new+=seg('69.1 101.5','69.1 99.5','0.50','F.Cu',2)+via('69.1 99.5',2)+seg('69.1 99.5','69.1 92.0','0.80','B.Cu',2)
new+=seg('88.0 92.0','88.0 103.0','0.80','B.Cu',2)

# GPIO12 arm expansion is routed wholly on F.Cu to avoid right-reverse B.Cu fanout.
new+=seg('50.0 52.94','55.0 52.94','0.28','F.Cu',14)
new+=seg('55.0 52.94','55.0 74.0','0.28','F.Cu',14)
new+=seg('55.0 74.0','43.0 74.0','0.28','F.Cu',14)

# RGB bulk capacitance requested for the 5V lighting output.
# C4 is hand-soldered, polarized radial electrolytic, 5 mm lead spacing.
new+='''  (footprint "C_Radial_5mm_RGB_Bulk" (layer "F.Cu") (at 80.0 103.0)
    (property "Reference" "C4" (at 0 -3.2 0) (layer "F.SilkS") hide)
    (property "Value" "470uF 16V" (at 0 3.2 0) (layer "F.Fab") hide)
    (fp_circle (center 0 0) (end 5 0) (stroke (width 0.18) (type default)) (fill none) (layer "F.Fab"))
    (pad "1" thru_hole circle (at 2.5 0) (size 2.6 2.6) (drill 1.0) (layers "*.Cu" "*.Mask") (net 2 "+5V"))
    (pad "2" thru_hole circle (at -2.5 0) (size 2.6 2.6) (drill 1.0) (layers "*.Cu" "*.Mask") (net 3 "GND"))
  )
  (gr_text "RGB 470uF 16V" (at 80 98.7) (layer "F.SilkS") (effects (font (size 0.85 0.85) (thickness 0.14))))
  (gr_text "+" (at 82.5 100.5) (layer "F.SilkS") (effects (font (size 1.0 1.0) (thickness 0.18))))
'''
# C4 positive goes directly to the RGB +5V output pad, avoiding the nearby JP4G ground pad.
new+=seg('82.5 103.0','88.0 103.0','0.80','B.Cu',2)

# Move the final human labels that native KiCad identified as overlapping.
label_moves={
    '(gr_text "R BRAKE ENABLE" (at 18.5 35.6)': '(gr_text "R BRAKE ENABLE" (at 36 35.6)',
    '(gr_text "R REVERSE ENABLE" (at 18.5 65.6)': '(gr_text "R REVERSE ENABLE" (at 36 65.6)',
    '(gr_text "ESP32 VIN <- 5V   |   ESP32 3V3 -> 3V3 RAILS   |   COMMON GND" (at 63 10.5)': '(gr_text "ESP32 VIN <- 5V   |   ESP32 3V3 -> 3V3 RAILS   |   COMMON GND" (at 63 13)',
    '(gr_text "5V ONLY - NO 36/42V BATTERY" (at 60 95.5)': '(gr_text "5V ONLY - NO 36/42V BATTERY" (at 60 84.5)',
    '(gr_text "PI GND" (at 66 101.5)': '(gr_text "PI GND" (at 61.5 101.5)',
}
for a,b in label_moves.items():
    s=s.replace(a,b,1)

# Insert all generated objects as children of the root kicad_pcb expression.
insert_at=s.rfind('\n)')
if insert_at < 0 or not s.lstrip().startswith('(kicad_pcb'):
    raise SystemExit('could not locate kicad_pcb root closing parenthesis')
s=s[:insert_at+1]+new+s[insert_at+1:]
out.write_text(s)
sha=hashlib.sha256(out.read_bytes()).hexdigest()
EXPECTED_OUT='3081ad9f4f2dd3dd22d0d82d2000a149e45859c197085c549902ffcde95cb8e3'
print('final board sha256',sha)
if sha!=EXPECTED_OUT:
    raise SystemExit('final board SHA mismatch')
